# Generated by Django 4.1.7 on 2023-06-05 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_spots',
            field=models.ManyToManyField(blank=True, null=True, related_name='visited_spots', to='guide.surfspot'),
        ),
        migrations.CreateModel(
            name='Surfboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('brand', models.CharField(blank=True, max_length=64, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('thickness', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('construction', models.CharField(blank=True, choices=[('EPS/Epoxy', 'EPS/Epoxy'), ('PU/Polyester', 'PU/Polyester'), ('Wood', 'Wood'), ('Other', 'Other')], max_length=64, null=True)),
                ('fin_setup', models.CharField(blank=True, choices=[('Single fin', 'Single fin'), ('Twin fin', 'Twin fin'), ('Thruster', 'Thruster'), ('Quad', 'Quad'), ('Five fin', 'Five fin'), ('Other', 'Other')], max_length=64, null=True)),
                ('tail', models.CharField(blank=True, choices=[('Pin', 'Pin'), ('Round', 'Round'), ('Square', 'Square'), ('Swallow', 'Swallow'), ('Squash', 'Squash'), ('Fish', 'Fish'), ('Other', 'Other')], max_length=64, null=True)),
                ('nose', models.CharField(blank=True, choices=[('Round', 'Round'), ('Pointed', 'Pointed'), ('Other', 'Other')], max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boards',
            field=models.ManyToManyField(blank=True, null=True, related_name='boards', to='guide.surfboard'),
        ),
    ]
