# Generated by Django 4.1.7 on 2023-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='danger',
            field=models.ManyToManyField(to='guide.danger'),
        ),
    ]
