# Generated by Django 4.1.7 on 2023-06-05 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_userprofile_friends_userprofile_visited_spots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='boards', to='guide.surfboard'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='visited_spots',
            field=models.ManyToManyField(blank=True, related_name='visited_spots', to='guide.surfspot'),
        ),
    ]
