# Generated by Django 4.1.7 on 2023-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_surfboard_length_alter_surfboard_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
